=== Bogdan1506/24_JavaST/task13/src/main/resources/pizzeria.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.training.by/entities"
        xmlns:tns="http://www.training.by/entities"
        elementFormDefault="qualified">
    <element name="entity" type="tns:Entity" abstract="true"/>
    <element name="order" type="tns:Order" substitutionGroup="tns:entity"/>
    <element name="entities">
        <complexType>
            <sequence>
                <element ref="tns:entity" maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>
    <complexType name="Entity">
        <sequence>
            <element name="id" type="int"/>
        </sequence>
    </complexType>
    <complexType name="Order">
        <complexContent>
            <extension base="tns:Entity">
                <sequence>
                    <element name="pizza" type="tns:Pizza"/>
                    <element name="orderPosition" type="tns:OrderPosition"/>
                    <element name="price" type="string"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>
    <complexType name="Pizza">
        <sequence>
            <element name="id" type="int"/>
            <element name="goods" type="tns:Goods"/>
            <element name="dough" type="tns:Dough"/>
            <element name="size" type="tns:Size"/>
        </sequence>
    </complexType>
    <complexType name="Goods">
        <sequence>
            <element name="id" type="int"/>
            <element name="name" type="string">
                <simpleType>
                    <restriction base="string">
                        <enumeration value="Pepperoni"/>
                        <enumeration value="Margherita"/>
                    </restriction>
                </simpleType>
            </element>
            <element name="description" type="string"/>
            <element name="price" type="double"/>
            <element name="picture" type="string"/>
        </sequence>
    </complexType>
    <complexType name="Dough">
        <sequence>
            <element name="id" type="int"/>
            <element name="name" type="int">
                <simpleType>
                    <restriction base="string">
                        <enumeration value="Thick"/>
                        <enumeration value="Thin"/>
                    </restriction>
                </simpleType>
            </element>
        </sequence>
    </complexType>
    <complexType name="Size">
        <sequence>
            <element name="id" type="int"/>
            <element name="name" type="int">
                <simpleType>
                    <restriction base="string">
                        <enumeration value="Small"/>
                        <enumeration value="Medium"/>
                        <enumeration value="Large"/>
                    </restriction>
                </simpleType>
            </element>
            <element name="coefficient" type="double"/>
        </sequence>
    </complexType>
    <complexType name="OrderPosition">
        <sequence>
            <element name="id" type="int"/>
            <element name="date" type="date"/>
            <element name="user" type="tns:User"/>
        </sequence>
    </complexType>
    <complexType name="User">
        <sequence>
            <element name="login" type="string"/>
            <element name="password" type="string"/>
        </sequence>
        <attribute name="role" type="int" use="required">
            <simpleType>
                <restriction base="int">
                    <enumeration value="0"/>
                    <enumeration value="1"/>
                    <enumeration value="2"/>
                </restriction>
            </simpleType>
        </attribute>
    </complexType>
</schema>

=== Bogdan1506/24_JavaST/task13/src/main/resources/pizzeria.xml
<?xml version ="1.0" encoding = "UTF-8"?>
<entities xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xmlns="http://www.training.by/entities"
          xsi:schemaLocation="http://www.training.by/entities  pizzeria.xsd">
    <order>
        <id>1</id>
        <price>6.9</price>
        <pizza>
            <id>1</id>
            <goods>
                <id>2</id>
                <name>Pepperoni</name>
                <description>Tomato sauce, mozzarella, pepperoni</description>
                <price>6.9</price>
                <picture>...</picture>
            </goods>
            <dough>
                <id>1</id>
                <name>Thick</name>
            </dough>
            <size>
                <id>1</id>
                <name>Large</name>
                <coefficient>1.0</coefficient>
            </size>
        </pizza>
        <orderPosition>
            <id>1</id>
            <date>2020-02-01</date>
            <user role="2">
                <id>7</id>
                <login>admin</login>
                <password>1234</password>
            </user>
        </orderPosition>
    </order>
    <order>
        <id>2</id>
        <price>6.9</price>
        <pizza>
            <id>1</id>
            <goods>
                <id>2</id>
                <name>Margherita</name>
                <description>Tomato sauce, mozzarella, pepperoni</description>
                <price>6.9</price>
                <picture>...</picture>
            </goods>
            <dough>
                <id>1</id>
                <name>Thick</name>
            </dough>
            <size>
                <id>1</id>
                <name>Large</name>
                <coefficient>1.0</coefficient>
            </size>
        </pizza>
        <orderPosition>
            <id>1</id>
            <date>2020-02-01</date>
            <user role="2">
                <id>7</id>
                <login>admin</login>
                <password>1234</password>
            </user>
        </orderPosition>
    </order>
</entities>
