=== Bogdan1506/24_JavaST/task13/src/main/resources/xmlTest2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.training.by/entities"
        xmlns:tns="http://www.training.by/entities"
        elementFormDefault="qualified">


<!--    <element name="entities">
        <complexType>
            <sequence>
                <element ref="tns:entities" minOccurs="1" maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>

    <complexType name="Entity">
        <sequence>
            <element name="id" type="int"/>
        </sequence>
    </complexType>

    <element name="entity" type="tns:Entity" abstract="true"/>
    <element name="order" type="tns:Order" substitutionGroup="tns:entity"/>

    <complexType name="Order">
        <complexContent>
            <extension base="tns:Entity">
                <sequence>
                    <element name="pizza" type="tns:Pizza"/>
                    <element name="orderPosition" type="tns:OrderPosition"/>
                    <element name="price" type="string"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="Pizza">
        <sequence>
            <element name="id" type="int"/>
            <element name="goods" type="tns:Goods"/>
            <element name="dough" type="tns:Dough"/>
            <element name="size" type="tns:Size"/>
        </sequence>
    </complexType>

    <complexType name="Goods">
        <sequence>
            <element name="id" type="int"/>
            <element name="name" type="string">
                <simpleType>
                    <restriction base="string">
                        <enumeration value="Pepperoni"/>
                        <enumeration value="Margherita"/>
                    </restriction>
                </simpleType>
            </element>
            <element name="description" type="string"/>
            <element name="price" type="int"/>
        </sequence>
    </complexType>

    <complexType name="Dough">
        <sequence>
            <element name="id" type="int"/>
            <element name="name" type="int">
                <simpleType>
                    <restriction base="int">
                        <enumeration value="Thick"/>
                        <enumeration value="Thin"/>
                    </restriction>
                </simpleType>
            </element>
        </sequence>
    </complexType>

    <complexType name="Size">
        <sequence>
            <element name="id" type="int"/>
            <element name="name" type="int">
                <simpleType>
                    <restriction base="int">
                        <enumeration value="Small"/>
                        <enumeration value="Medium"/>
                        <enumeration value="Large"/>
                    </restriction>
                </simpleType>
            </element>
        </sequence>
    </complexType>

    <complexType name="OrderPosition">
        <sequence>
            <element name="id" type="int"/>
            <element name="date" type="date"/>
            <element name="user" type="tns:User"/>
        </sequence>
    </complexType>

    <complexType name="User">
        <sequence>
            <element name="login" type="string"/>
            <element name="pass" type="string"/>
            <element name="email" type="string"/>
        </sequence>
        <attribute name="role" type="int" use="required">
            <simpleType>
                <restriction base="int">
                    <enumeration value="0"/>
                    <enumeration value="1"/>
                    <enumeration value="2"/>
                </restriction>
            </simpleType>
        </attribute>
    </complexType>

</schema>-->


        <element name="entity" type="tns:Entity" abstract="true"></element>
        <element name="user" type="tns:User" substitutionGroup="tns:entity"></element>
        <element name="order" type="tns:Order" substitutionGroup="tns:entity"></element>
        <element name="entities">
            <complexType>
                <sequence>
                    <element ref="tns:entity"
                             minOccurs="1"
                             maxOccurs="unbounded"/>
                </sequence>
            </complexType>
        </element>


        <complexType name="Entity">
            <sequence>
                <element name="id" type="int"/>
            </sequence>
        </complexType>

        <complexType name="User">
            <complexContent>
                <extension base="tns:Entity">
                    <sequence>
                        <element name="login" type="string"/>
                        <element name="pass" type="string"/>
                        <element name="email" type="string"/>
                        <element name="userInfo" type="tns:UserInfo"/>
                    </sequence>
                    <attribute name="role" type="int" use="required">
                        <simpleType>
                            <restriction base="int">
                                <enumeration value="0"></enumeration>
                                <enumeration value="1"></enumeration>
                                <enumeration value="2"></enumeration>
                            </restriction>
                        </simpleType>
                    </attribute>
                </extension>

            </complexContent>

        </complexType>
        <complexType name="UserInfo">
            <sequence>
                <element name="name" type="string"/>
                <element name="surname" type="string"/>
                <element name="phoneNumber" type="string"/>
            </sequence>
        </complexType>

        <complexType name="Order">
            <complexContent>
                <extension base="tns:Entity">
                    <sequence>
                        <element name="date" type="date"/>
                        <element name="deliviredate" type="date"/>
                        <element name="price" type="string"/>
                        <element name="productlist" type="tns:ProductList"/>
                    </sequence>
                    <attribute name="status" type="string" use="required"/>
                </extension>
            </complexContent>
        </complexType>
        <complexType name="ProductList">
            <sequence>
                <element name="product" type="tns:Product" minOccurs="1"
                         maxOccurs="unbounded"/>
            </sequence>
        </complexType>
        <complexType name="Product">
            <complexContent>
                <extension base="tns:Entity">
                    <sequence>
                        <element name="quantity" type="int"/>
                    </sequence>
                </extension>
            </complexContent>
        </complexType>

    </schema>

=== Bogdan1506/24_JavaST/task13/src/main/resources/xmlTest2.xml
<?xml version ="1.0" encoding = "UTF 8"?>
<entities xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xmlns="http://www.training.by/entities"
          xsi:schemaLocation="http://www.training.by/entities  xmlTest2.xsd">
<!--    <order>
        <id>1</id>
        <pizza>
            <id>1</id>
            <goods>
                <id>2</id>
                <name>Pepperoni</name>
                <description>Tomato sauce, mozzarella, pepperoni</description>
                <price>6.9</price>
                <picture>...</picture>
            </goods>
            <dough>
                <id>1</id>
                <name>Thick</name>
            </dough>
            <size>
                <id>1</id>
                <name>Small</name>
                <coefficient>1.0</coefficient>
            </size>
        </pizza>
        <orderPosition>
            <id>1</id>
            <date>2020-02-01</date>
            <user role="0">
                <login>admin</login>
                <password>1234</password>
            </user>
        </orderPosition>
        <price>6.9</price>
    </order>
</entities>-->

         <user role="2">
             <id>1</id>
             <login>admin</login>
             <pass>123456</pass>
             <email>admin@gmail.com</email>
             <userInfo>
                 <name>Артем</name>
                 <surname>Колганов</surname>
                 <phoneNumber>291111111</phoneNumber>
             </userInfo>
         </user>
         <order status="compilation">
             <id>2</id>
             <date>2020-02-01</date>
             <deliviredate>2020-03-05</deliviredate>
             <price>30.5</price>
             <productlist>
                 <product>
                     <id>1</id>
                     <quantity>3</quantity>
                 </product>
                 <product>
                     <id>2</id>
                     <quantity>5</quantity>
                 </product>
             </productlist>
         </order>
     </entities>
